version: "3"
services:
    www:
        build: .
        ports:
            - "443:443" 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
            - mail
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    mail:
        image: namshi/smtp
        container_name: camagru_smtp
        ports:
          - "26:25"
        environment:
            GMAIL_USER: $GMAIL_USER
            GMAIL_PASSWORD: $GMAIL_PASSWORD 
volumes:
    persistent:
